// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/ReplaceForxyz.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class ReplaceForxyz {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object Alph=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=26;
      if ($opEqualY($invokeField("length",args),0)) {
        $line=27;
        Alph=$fix(GCollections.asSet('a','b','c','d'));
      }
      else {
        $line=29;
        gold.structures.set.ISet $v1=$newSet();
        int $v3=$int(0);
        int $v4=$int($invokeMethod("length",((java.lang.String[])args)[$int(0)],new Object[]{}))-1;
        $v2:for (int i=$v3; i<=$v4; i++) {
          $v1.add($invokeMethod("charAt",((java.lang.String[])args)[$int(0)],new Object[]{i}));
        }
        Alph=$fix($opDiffeY($v1,GCollections.asSet('$','#')));
      }
      $line=32;
      Object deCoder=$fix(ReplaceForxyz.createTransducer(Alph));
      $line=33;
      System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY($opAdditY("Input strings of the form xyz:W#. with x, y, over ",Alph),"and W  over   "),Alph),"* (end with an empty string)")}));
      $line=33;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,deCoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"main",$line);
    }
  }
  public static Object cutString(String reading) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=37;
      char[] characters=$cast(char[].class,$fix(((java.lang.String)reading).toCharArray()));
      $line=37;
      Integer len=$cast(Integer.class,$fix(0));
      $line=37;
      String out=$cast(String.class,$fix(""));
      $line=39;
      while (true) {
        if (!($opLesstY(len,3))) break;
        $line=40;
        out=$cast(String.class,$fix($opAdditY(out,Character.toString($cast(char.class,((char[])characters)[$int(len)])))));
        $line=40;
        len=$cast(Integer.class,$fix($opAdditY(len,1)));
      }
      $line=42;
      $result=out;
      if (true) break $try;
      $line=43;
      $rethrow(new RuntimeException("The function \"cutString(reading:String)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"cutString",$line);
    }
    return $result;
  }
  public static ITransducer createTransducer(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=46;
      gold.structures.set.ISet $v5=$newSet();
      $v6:for (Object position:GCollections.unmodifiableCollection(GCollections.asSet(0,1))) {
        gold.structures.set.ISet $v7=$newSet();
        $v8:for (Object p:GCollections.unmodifiableCollection(A)) {
          for (Object q:GCollections.unmodifiableCollection(A)) {
            for (Object r:GCollections.unmodifiableCollection(A)) {
              $v7.add($opAdditY($opAdditY($opAdditY($opAdditY("",p),q),r),"!"));
            }
          }
        }
        for (Object firstSet:GCollections.unmodifiableCollection($opUnionY($v7,GCollections.asSet("Asterisk","Asterisk!",GCollections.emptySet())))) {
          gold.structures.set.ISet $v9=$newSet();
          $v10:for (Object p:GCollections.unmodifiableCollection(A)) {
            $v9.add($opAdditY("",p));
          }
          gold.structures.set.ISet $v11=$newSet();
          $v12:for (Object p:GCollections.unmodifiableCollection(A)) {
            for (Object q:GCollections.unmodifiableCollection(A)) {
              $v11.add($opAdditY($opAdditY("",p),q));
            }
          }
          gold.structures.set.ISet $v13=$newSet();
          $v14:for (Object p:GCollections.unmodifiableCollection(A)) {
            for (Object q:GCollections.unmodifiableCollection(A)) {
              for (Object r:GCollections.unmodifiableCollection(A)) {
                $v13.add($opAdditY($opAdditY($opAdditY("",p),q),r));
              }
            }
          }
          gold.structures.set.ISet $v15=$newSet();
          $v16:for (Object p:GCollections.unmodifiableCollection(A)) {
            for (Object q:GCollections.unmodifiableCollection(A)) {
              for (Object r:GCollections.unmodifiableCollection(A)) {
                $v15.add($opAdditY($opAdditY($opAdditY($opAdditY("",p),q),r),"!"));
              }
            }
          }
          for (Object secondSet:GCollections.unmodifiableCollection($opUnionY($opUnionY($opUnionY($opUnionY($v9,$v11),$v13),$v15),GCollections.asSet("Asterisk","Asterisk!")))) {
            $v5.add(GCollections.asList(position,firstSet,secondSet));
          }
        }
      }
      Object States=$fix($opUnionY(GCollections.asSet("Start","Final","Error"),$v5));
      $line=46;
      Object InAlphabet=$fix(GCollections.asSet('a','b','c','d','!','#','*'));
      $line=46;
      Object OutAlphabet=$fix(GCollections.asSet('a','b','c','d','!','#'));
      $line=46;
      Object initState=$fix("Start");
      $line=46;
      Object finalStates=$fix(GCollections.asSet("Final"));
      $line=48;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{States,InAlphabet,OutAlphabet,initState,finalStates,new GMethod(ReplaceForxyz.class,"\u03B41"),new GMethod(ReplaceForxyz.class,"h1"),new GMethod(ReplaceForxyz.class,"g")});
      if (true) break $try;
      $line=49;
      $rethrow(new RuntimeException("The function \"createTransducer(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object g(Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $result="";
      if (true) break $try;
      $line=52;
      $rethrow(new RuntimeException("The function \"g(x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"g",$line);
    }
    return $result;
  }
  public static Object \u03B41(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=55;
      Object s=$fix(GCollections.asSet('a','b','c','d'));
      $line=56;
      if (($opEqualY(q,"Start")&&$opMembrY(\u03C3,s))) {
        $line=57;
        $result=GCollections.asList(1,GCollections.emptySet(),Character.toString($cast(char.class,\u03C3)));
        if (true) break $try;
      }
      else {
        $line=58;
        if (($opEqualY(q,"Start")&&$opEqualY(Character.toString($cast(char.class,\u03C3)),"#"))) {
          $line=59;
          $result="Final";
          if (true) break $try;
        }
        else {
          $line=61;
          $result="Error";
          if (true) break $try;
        }
      }
      $line=63;
      $rethrow(new RuntimeException("The function \"\u03B41(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object \u03B41(java.lang.Iterable $v17, Object reading) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v18=GCollections.unmodifiableCollection($v17).iterator();
      Object position=$v18.next();
      Object firstSet=$v18.next();
      Object secondSet=$v18.next();
      $line=66;
      Object s=$fix(GCollections.asSet('a','b','c','d'));
      $line=68;
      if (($opEqualY($opAbsolY(secondSet),1)&&$opMembrY(reading,s))) {
        $line=69;
        $result=GCollections.asList(position,firstSet,$opAdditY(secondSet,reading));
        if (true) break $try;
      }
      else {
        $line=71;
        if (($opEqualY($opAbsolY(secondSet),2)&&$opMembrY(reading,s))) {
          $line=72;
          $result=GCollections.asList(position,firstSet,$opAdditY(secondSet,reading));
          if (true) break $try;
        }
        else {
          $line=74;
          if (($opEqualY($opAbsolY(secondSet),3)&&$opEqualY(reading,'!'))) {
            $line=76;
            if (($opEqualY(position,0)&&$opEqualY(firstSet,$opAdditY(secondSet,reading)))) {
              $line=77;
              $result="Error";
              if (true) break $try;
            }
            else {
              $line=79;
              $result=GCollections.asList(position,firstSet,$opAdditY(secondSet,reading));
              if (true) break $try;
            }
          }
          else {
            $line=82;
            if ((($opEqualY($opAbsolY(secondSet),3)&&$opEqualY(reading,'#'))&&!$opEqualY(position,1))) {
              $line=83;
              if (($opEqualY(position,0)&&$opEqualY(firstSet,$opAdditY(secondSet,"!")))) {
                $line=84;
                $result="Error";
                if (true) break $try;
              }
              else {
                $line=86;
                $result="Final";
                if (true) break $try;
              }
            }
            else {
              $line=89;
              if (($opEqualY($opAbsolY(secondSet),4)&&$opMembrY(reading,s))) {
                $line=90;
                $result=GCollections.asList($opModulY($opAdditY(position,1),2),secondSet,Character.toString($cast(char.class,reading)));
                if (true) break $try;
              }
              else {
                $line=91;
                if ((($opEqualY($opAbsolY(secondSet),4)&&$opEqualY(reading,'*'))&&!$opEqualY(position,0))) {
                  $line=92;
                  $result=GCollections.asList($opModulY($opAdditY(position,1),2),secondSet,"Asterisk");
                  if (true) break $try;
                }
                else {
                  $line=93;
                  if (($opEqualY(secondSet,"Asterisk")&&$opEqualY(reading,'!'))) {
                    $line=94;
                    $result=GCollections.asList(position,firstSet,"Asterisk!");
                    if (true) break $try;
                  }
                  else {
                    $line=95;
                    if ((($opEqualY(secondSet,"Asterisk")&&$opEqualY(reading,'#'))&&!$opEqualY(position,1))) {
                      $line=96;
                      $result="Final";
                      if (true) break $try;
                    }
                    else {
                      $line=97;
                      if (($opEqualY(secondSet,"Asterisk!")&&$opMembrY(reading,s))) {
                        $line=98;
                        $result=GCollections.asList($opModulY($opAdditY(position,1),2),secondSet,Character.toString($cast(char.class,reading)));
                        if (true) break $try;
                      }
                      else {
                        $line=100;
                        $result="Error";
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=102;
      $rethrow(new RuntimeException("The function \"\u03B41(\u27E8position,firstSet,secondSet\u27E9:java.lang.Iterable,reading:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object h1(Object state) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=104;
      $result="";
      if (true) break $try;
      $line=105;
      $rethrow(new RuntimeException("The function \"h1(state:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"h1",$line);
    }
    return $result;
  }
  public static Object h1(java.lang.Iterable $v19) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v20=GCollections.unmodifiableCollection($v19).iterator();
      Object position=$v20.next();
      Object firstSet=$v20.next();
      Object secondSet=$v20.next();
      $line=108;
      $result="";
      if (true) break $try;
      $line=109;
      $rethrow(new RuntimeException("The function \"h1(\u27E8position,firstSet,secondSet\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"h1",$line);
    }
    return $result;
  }
  public static Object g(Object state, Object reading) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=112;
      if (($opEqualY(state,"Start")&&$opEqualY(Character.toString($cast(char.class,reading)),"#"))) {
        $line=113;
        $result=reading;
        if (true) break $try;
      }
      else {
        $line=115;
        $result="";
        if (true) break $try;
      }
      $line=117;
      $rethrow(new RuntimeException("The function \"g(state:Object,reading:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"g",$line);
    }
    return $result;
  }
  public static Object g(java.lang.Iterable $v21, Object reading) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v22=GCollections.unmodifiableCollection($v21).iterator();
      Object position=$v22.next();
      Object firstSet=$v22.next();
      Object secondSet=$v22.next();
      $line=120;
      Object s=$fix(GCollections.asSet('a','b','c','d'));
      $line=121;
      if (($opEqualY($opAbsolY(secondSet),2)&&$opMembrY(reading,s))) {
        $line=122;
        $result=$opAdditY(secondSet,reading);
        if (true) break $try;
      }
      else {
        $line=123;
        if (($opEqualY($opAbsolY(secondSet),3)&&$opEqualY(reading,'!'))) {
          $line=124;
          $result=reading;
          if (true) break $try;
        }
        else {
          $line=125;
          if (($opEqualY($opAbsolY(secondSet),3)&&$opEqualY(reading,'#'))) {
            $line=126;
            $result=reading;
            if (true) break $try;
          }
          else {
            $line=127;
            if (($opEqualY($opAbsolY(secondSet),4)&&$opEqualY(reading,'*'))) {
              $line=128;
              $result=ReplaceForxyz.cutString($cast(java.lang.String.class,secondSet));
              if (true) break $try;
            }
            else {
              $line=129;
              if (($opEqualY(secondSet,"Asterisk")&&$opEqualY(reading,'!'))) {
                $line=130;
                $result=reading;
                if (true) break $try;
              }
              else {
                $line=131;
                if (($opEqualY(secondSet,"Asterisk")&&$opEqualY(reading,'#'))) {
                  $line=132;
                  $result=reading;
                  if (true) break $try;
                }
                else {
                  $line=134;
                  $result="";
                  if (true) break $try;
                }
              }
            }
          }
        }
      }
      $line=136;
      $rethrow(new RuntimeException("The function \"g(\u27E8position,firstSet,secondSet\u27E9:java.lang.Iterable,reading:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"g",$line);
    }
    return $result;
  }
}
